### ISSUE TITLE
"expected `u8`, found `i8`" when building

### ISSUE THREAD

**Issue by root2185** [calculon102/xgifwallpaper#10]
```

   Compiling ctrlc v3.1.7
error[E0308]: mismatched types
   --> src/xcontext.rs:125:34
    |
125 |     let atom = get_atom(display, window_id.as_ptr() as *const i8, x11::xlib::True);
    |                --------          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u8`, found `i8`
    |                |
    |                arguments to this function are incorrect
    |
    = note: expected raw pointer `*const u8`
               found raw pointer `*const i8`
note: function defined here
   --> src/xatoms.rs:44:8
    |
44  | pub fn get_atom(display: *mut Display, name: *const c_char, only_if_exists: c_int) -> c_ulong {
    |        ^^^^^^^^ ---------------------  -------------------  ---------------------

For more information about this error, try `rustc --explain E0308`.

```
When compiling I have that error, you need indeed to change it to `u8`.

**Comment by calculon102** [comment]
Hi @root2185 ,

thanks for your report. I'm unable to repeat this error, using cargo build on master branch with rustc 1.67.0..

How do you build? Which branch? Which rust version?

**Comment by root2185** [comment]
I had this error using version 0.3.1.
```
# Maintainer: root2185
pkgname=xgifwallpaper
pkgver=0.3.1
pkgrel=6
pkgdesc="Use an animated GIF as wallpaper on X11 systems"
arch="all"
url="https://github.com/calculon102/xgifwallpaper"
license="GPL-3.0"
depends="libx11 libxau libxcb libxdmcp libxinerama libxext"
makedepends="gcc git rust cargo"
source="$pkgname-$pkgver.tar.gz::https://github.com/calculon102/xgifwallpaper/archive/refs/tags/v$pkgver.tar.gz"

build() {
	
	sed -i 's/\ as \*const\ i8/\ as\ \*const\ u8/g' src/xcontext.rs
  	cargo build --release --locked --all-features --target-dir=target
}

package() {
	install -Dm 755 target/release/${pkgname} -t "${pkgdir}/usr/bin"
}
sha512sums="
211407c769c90131c7a7f1ff7b634915e21d692107c158457e6dc2531b6d29534933f2e03edccd36f4527c0995ed93daf67b4ca0bbf6797cf9e69133855be73e  xgifwallpaper-0.3.1.tar.gz
"
```
`rust 1.64.0-r2`
That is on pmOS, based on Alpine Linux.
On anther device I used the AUR version and it worked fine.

**Comment by calculon102** [comment]
@root2185 Thank you for the details. I think I understand the problem now.

The actual type of `c_char` is platform-dependent. Thus `i8` on my and your other Linux machine, but `u8` on pmOS.

The solution should be altering the line
```
let atom = get_atom(display, window_id.as_ptr() as *const i8, x11::xlib::True);
```

to
```
let atom = get_atom(display, window_id.as_ptr() as *const c_char, x11::xlib::True);
```
in `xcontext.rs`

Can you try that on both of your machines? In my tests, this already works.

**Comment by root2185** [comment]
```
...
   Compiling ctrlc v3.1.7
error[E0412]: cannot find type `c_char` in this scope
   --> src/xcontext.rs:125:63
    |
125 |     let atom = get_atom(display, window_id.as_ptr() as *const c_char, x11::xlib::True);
    |                                                               ^^^^^^
    |
help: a builtin type with a similar name exists
    |
125 |     let atom = get_atom(display, window_id.as_ptr() as *const char, x11::xlib::True);
    |                                                               ~~~~
help: consider importing one of these items
    |
3   | use core::ffi::c_char;
    |
3   | use libc::c_char;
    |
3   | use std::ffi::c_char;
    |
3   | use std::os::raw::c_char;
    |

For more information about this error, try `rustc --explain E0412`.

```

**Comment by calculon102** [comment]
Ah, of course, sorry!  I omitted a second, necessary change in `xcontext.rs`.

Please replace
```
use std::os::raw::{c_int, c_uint, c_ulong};
```
with
```
use std::os::raw::{c_char, c_int, c_uint, c_ulong};
```
at the top the the file.

Then it should work. Thank you!

**Comment by root2185** [comment]
Yes it does.

**Comment by calculon102** [comment]
@root2185 Thank you for your help!
